migrated to null-safety, fixed deprecation errors
dhruvilp/humanitarian_icons pull request #1
Opened 2021-11-04 12:20 UTC by jabguru

Thanks for the package, using it but needed to migrate to null safety.

2021-11-12 22:26 UTC, dhruvilp commented on pubspec.yaml
> -author: Dhruvil Patel
replace with 
```maintainer: Dhruvil Patel (@dhruvilp )```

2021-11-12 22:30 UTC, dhruvilp requested changes
Hey,

Thanks for raising a PR, really appreciate it!
Can you please ignore/delete these files/folders and commit again:

.dart_tool/package_config.json
.dart_tool/package_config_subset
.dart_tool/version
.packages
example/.dart_tool/package_config.json
example/.dart_tool/package_config_subset
example/.dart_tool/version
example/.packages
example/pubspec.lock
pubspec.lock

It's not good practice to commit files and folders that start with ".".

Thanks man!

2021-11-13 19:34 UTC, jabguru commented
Alright, made the changes now, you can check it out, thanks.

2021-11-13 20:08 UTC, dhruvilp approved these changes
Perfect, thanks!

2021-11-13 20:08 UTC, merged